#!/usr/bin/env bash

set -e

DIR="$( cd "$( dirname "$0" )" && pwd )"

DOTFILES=`ls -a -1 | egrep "^\.\w" | grep -v "^\.git$"`

echo "$DOTFILES" | while read -r FILE
do
  SOURCE="$DIR/$FILE"
  TARGET="$HOME/$FILE"
  echo "$SOURCE -> $TARGET";
  rm -f "$TARGET"
  ln -s "$SOURCE" "$TARGET"
done
